### ISSUE TITLE
Why is CLS_ORIENTATION False for barriers in dataset?

### ISSUE THREAD

**Issue by harsanyidani** [tjiiv-cprg/EPro-PnP-v2#7]
I see that in the code:
https://github.com/tjiiv-cprg/EPro-PnP-v2/blob/85215de8002dbd8523ee8eaaf1bae85b47179ebe/EPro-PnP-Det_v2/epropnp_det/datasets/nuscenes3d_dataset.py#L41
`CLS_ORIENTATION ` is set to false for barriers. Why is it this way? 

[nuScenes ](https://arxiv.org/pdf/1903.11027.pdf) states about the TP metrics in the detection task:

> We omit measurements for classes where they are not well defined: AVE for cones and barriers since they are stationary; AOE of cones since they do not have a well defined orientation; and AAE for cones and barriers since there are no attributes defined on these classes.

So orientation should be computed for barriers too.

Or did I misunderstood the meaning of `CLS_ORIENTATION `?

**Comment by harsanyidani** [comment]
Now I see that AOE is calculated for barriers too during evaluation. Am I seeing it right that `CLS_ORIENTATION` is only used for visualization purposes here:

https://github.com/tjiiv-cprg/EPro-PnP-v2/blob/main/EPro-PnP-Det_v2/epropnp_det/models/detectors/epropnp_det.py#L113-L119

An nowhere else?

**Comment by Lakonik** [comment]
> Now I see that AOE is calculated for barriers too during evaluation. Am I seeing it right that `CLS_ORIENTATION` is only used for visualization purposes here:
> 
> https://github.com/tjiiv-cprg/EPro-PnP-v2/blob/main/EPro-PnP-Det_v2/epropnp_det/models/detectors/epropnp_det.py#L113-L119
> 
> And nowhere else? Can you please clarify what it's purpose is?

That's right, `CLS_ORIENTATION` is only used for visualization. Orientations of all objects are handled in a probabilistic manner during training and inference so it doesn't matter whether an object is symmetric or not.

**Comment by harsanyidani** [comment]
Thanks!
