### ISSUE TITLE
Question: What are the main differences compared to the original repository?

### ISSUE THREAD

**Issue by harsanyidani** [tjiiv-cprg/EPro-PnP-v2#8]
I've spent some time searching, I would be thankful if you could point out the main differences, so I know where to look.

Thanks in advance!

**Comment by Lakonik** [comment]
Hi! The high-level differences are stated in the [README](https://github.com/tjiiv-cprg/EPro-PnP-v2?tab=readme-ov-file#models). For more details, you can compare the codes of the two repositories.

**Comment by harsanyidani** [comment]
Oops, I missed that, thanks!
